# This is the final, correct version.
services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    # This block is the key to fixing the race condition.
    depends_on:
      mysql-db:
        condition: service_healthy # It WILL wait for MySQL.
      mongo-db:
        condition: service_started
      redis:
        condition: service_started
    restart: always

  mysql-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    # This block tells Docker how to know when MySQL is ready.
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mysql_data:
  mongo_data:
  redis_data: